from __future__ import annotations

import argparse
import sys
from pathlib import Path

from marume_data.extract import scaffold_rules_csv_from_manifest, scaffold_rules_csv_from_pdf


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Create a rules CSV scaffold from an official DPC PDF.")
    source = parser.add_mutually_exclusive_group(required=True)
    source.add_argument("--manifest", type=Path, help="manifest.json generated by fetch_mhlw.py.")
    source.add_argument("--pdf", type=Path, help="Official DPC PDF path.")
    parser.add_argument("--output", type=Path, required=True, help="Output CSV path.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        output_path = _run(args)
    except FileNotFoundError as exc:
        print(f"入力ファイルが見つかりません: {exc}", file=sys.stderr)
        return 1
    print(output_path)
    return 0


def _run(args: argparse.Namespace) -> Path:
    if args.manifest is not None:
        return scaffold_rules_csv_from_manifest(args.manifest, args.output)
    return scaffold_rules_csv_from_pdf(args.pdf, args.output)


if __name__ == "__main__":
    raise SystemExit(main())
