from __future__ import annotations

import argparse
import sys
from pathlib import Path

from marume_data.fetch import load_manifest, resolve_page_path, resolve_rules_csv_path


def parse_args() -> argparse.Namespace:
    """Parse CLI arguments for snapshot JSON generation."""

    parser = argparse.ArgumentParser(description="Transform fetched MHLW assets into a snapshot JSON.")
    parser.add_argument("--input", type=Path, default=None, help="Fetched HTML source file path.")
    parser.add_argument(
        "--manifest",
        type=Path,
        default=None,
        help="Optional manifest.json generated by fetch_mhlw.py.",
    )
    parser.add_argument("--output", type=Path, required=True, help="Output snapshot JSON path.")
    parser.add_argument(
        "--rules-csv",
        type=Path,
        default=None,
        help="Optional CSV file that contains flattened DPC rules.",
    )
    parser.add_argument("--fiscal-year", type=int, required=True, help="Fiscal year to stamp in output.")
    parser.add_argument(
        "--source-url",
        default=None,
        help="Source URL recorded in the snapshot.",
    )
    return parser.parse_args()


def main() -> int:
    """Transform fetched MHLW assets into one normalized snapshot JSON file."""

    args = parse_args()
    from marume_data.transform import parse_mhlw_dpc_page, write_snapshot_from_sources

    try:
        input_path = _resolve_input_path(args.input, args.manifest)
        if args.rules_csv is not None and not args.rules_csv.exists():
            raise FileNotFoundError(args.rules_csv)
        rules_csv_path = args.rules_csv or _resolve_rules_csv(args.manifest)
        source_url = _resolve_source_url(args.source_url, args.manifest)
        html = input_path.read_text(encoding="utf-8")
        metadata = parse_mhlw_dpc_page(
            html=html,
            base_url=source_url,
        )
        write_snapshot_from_sources(
            output_path=args.output,
            fiscal_year=args.fiscal_year,
            source_url=source_url,
            page_metadata=metadata,
            rules_csv_path=rules_csv_path,
        )
    except FileNotFoundError as exc:
        print(f"入力ファイルが見つかりません: {exc}", file=sys.stderr)
        return 1
    except OSError as exc:
        print(f"ファイル操作に失敗しました: {exc}", file=sys.stderr)
        return 1
    except ValueError as exc:
        print(f"入力値が不正です: {exc}", file=sys.stderr)
        return 1
    except Exception as exc:
        print(f"snapshot 生成に失敗しました: {exc}", file=sys.stderr)
        return 1
    print(args.output)
    return 0


def _resolve_input_path(input_path: Path | None, manifest_path: Path | None) -> Path:
    """Resolve the HTML input path from explicit input or manifest."""

    if input_path is not None:
        if not input_path.exists():
            raise FileNotFoundError(input_path)
        return input_path
    if manifest_path is not None:
        resolved = resolve_page_path(manifest_path)
        if not resolved.exists():
            raise FileNotFoundError(resolved)
        return resolved
    raise ValueError("--input か --manifest のどちらかは必須です")


def _resolve_rules_csv(manifest_path: Path | None) -> Path | None:
    """Resolve an optional rules CSV path from the manifest."""

    if manifest_path is None:
        return None
    resolved = resolve_rules_csv_path(manifest_path)
    if resolved is not None and not resolved.exists():
        raise FileNotFoundError(resolved)
    return resolved


def _resolve_source_url(source_url: str | None, manifest_path: Path | None) -> str:
    """Resolve the source URL from an explicit flag or a manifest."""

    if source_url:
        return source_url
    if manifest_path is not None:
        manifest = load_manifest(manifest_path)
        manifest_page_url = manifest.get("page_url")
        if manifest_page_url:
            return str(manifest_page_url)
        raise KeyError(f"page_url is missing in manifest: {manifest_path}")
    raise ValueError("--source-url か --manifest のどちらかで source URL を指定してください")


if __name__ == "__main__":
    raise SystemExit(main())
