from __future__ import annotations

import argparse
from pathlib import Path

from marume_data.fetch import resolve_page_path, resolve_rules_csv_path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Transform fetched MHLW assets into a snapshot JSON.")
    parser.add_argument("--input", type=Path, default=None, help="Fetched HTML source file path.")
    parser.add_argument(
        "--manifest",
        type=Path,
        default=None,
        help="Optional manifest.json generated by fetch_mhlw.py.",
    )
    parser.add_argument("--output", type=Path, required=True, help="Output snapshot JSON path.")
    parser.add_argument(
        "--rules-csv",
        type=Path,
        default=None,
        help="Optional CSV file that contains flattened DPC rules.",
    )
    parser.add_argument("--fiscal-year", type=int, default=2026, help="Fiscal year to stamp in output.")
    parser.add_argument(
        "--source-url",
        default="https://www.mhlw.go.jp/stf/newpage_67729.html",
        help="Source URL recorded in the snapshot.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    from marume_data.transform import parse_mhlw_dpc_page, write_snapshot_from_sources

    input_path = _resolve_input_path(args.input, args.manifest)
    rules_csv_path = args.rules_csv or _resolve_rules_csv(args.manifest)
    html = input_path.read_text(encoding="utf-8")
    metadata = parse_mhlw_dpc_page(
        html=html,
        base_url=args.source_url,
    )
    write_snapshot_from_sources(
        output_path=args.output,
        fiscal_year=args.fiscal_year,
        source_url=args.source_url,
        page_metadata=metadata,
        rules_csv_path=rules_csv_path,
    )
    print(args.output)
    return 0


def _resolve_input_path(input_path: Path | None, manifest_path: Path | None) -> Path:
    if input_path is not None:
        if not input_path.exists():
            raise FileNotFoundError(input_path)
        return input_path
    if manifest_path is not None:
        resolved = resolve_page_path(manifest_path)
        if not resolved.exists():
            raise FileNotFoundError(resolved)
        return resolved
    raise ValueError("--input か --manifest のどちらかは必須です")


def _resolve_rules_csv(manifest_path: Path | None) -> Path | None:
    if manifest_path is None:
        return None
    resolved = resolve_rules_csv_path(manifest_path)
    if resolved is not None and not resolved.exists():
        raise FileNotFoundError(resolved)
    return resolved


if __name__ == "__main__":
    raise SystemExit(main())
